# This is a config for E2B sandbox template.
# You can use template ID (sbkglzin4xjehlfr4rhs) or template name (web_builder-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("web_builder-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("web_builder-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('web_builder-nextjs-test')

team_id = "3c4bd19b-0c2b-4d58-9d11-51a21ccc20b4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "web_builder-nextjs-test"
template_id = "sbkglzin4xjehlfr4rhs"
